# Generated by Django 4.1.7 on 2023-02-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_alter_produit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
