# Generated by Django 4.1.7 on 2023-03-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produit_catégorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category_type',
            field=models.CharField(choices=[('Al', 'Alimentaire'), ('Mb', 'Meuble'), ('Sn', 'Sanitaire'), ('Vs', 'Vaisselle'), ('Vt', 'Vêtement'), ('Jx', 'Jouets'), ('Lg', 'Linge de Maison'), ('Bj', 'Bijoux'), ('Dc', 'Décor'), ('El', 'Electroménager'), ('Fr', 'Frais')], default='Al', max_length=2),
        ),
    ]
